-- Subscription entitlements, knowledge citation grants, and bean square metadata.

ALTER TABLE user_bean_cards
    ADD COLUMN IF NOT EXISTS public_comment text,
    ADD COLUMN IF NOT EXISTS source_bean_card_id text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'user_bean_cards_source_bean_card_id_fkey'
    ) THEN
        ALTER TABLE user_bean_cards
            ADD CONSTRAINT user_bean_cards_source_bean_card_id_fkey
            FOREIGN KEY (source_bean_card_id) REFERENCES user_bean_cards(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_user_bean_cards_source_bean_card_id
    ON user_bean_cards(source_bean_card_id);

CREATE TABLE IF NOT EXISTS user_knowledge_article_grants (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    slug text NOT NULL,
    trace_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS user_knowledge_article_grants_user_slug_uq
    ON user_knowledge_article_grants(user_id, slug);

CREATE INDEX IF NOT EXISTS ix_user_knowledge_article_grants_user_id
    ON user_knowledge_article_grants(user_id);

CREATE INDEX IF NOT EXISTS ix_user_knowledge_article_grants_slug
    ON user_knowledge_article_grants(slug);
