-- Payment records for Alipay one-time purchases and Stripe subscriptions.

ALTER TABLE user_profiles
    ADD COLUMN IF NOT EXISTS plan_source text NOT NULL DEFAULT 'manual',
    ADD COLUMN IF NOT EXISTS plan_expires_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS billing_payment_orders (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    provider text NOT NULL,
    plan text NOT NULL,
    interval text NOT NULL,
    amount_cents integer NOT NULL,
    currency text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    external_order_id text,
    external_transaction_id text,
    external_subscription_id text,
    checkout_url text,
    qr_code text,
    provider_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    period_start timestamp with time zone,
    period_end timestamp with time zone,
    expires_at timestamp with time zone,
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS billing_payment_orders_provider_external_uq
    ON billing_payment_orders(provider, external_order_id)
    WHERE external_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_billing_payment_orders_user_id ON billing_payment_orders(user_id);
CREATE INDEX IF NOT EXISTS ix_billing_payment_orders_provider ON billing_payment_orders(provider);
CREATE INDEX IF NOT EXISTS ix_billing_payment_orders_status ON billing_payment_orders(status);
CREATE INDEX IF NOT EXISTS ix_billing_payment_orders_external_transaction_id ON billing_payment_orders(external_transaction_id);
CREATE INDEX IF NOT EXISTS ix_billing_payment_orders_external_subscription_id ON billing_payment_orders(external_subscription_id);

CREATE TABLE IF NOT EXISTS billing_subscriptions (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    provider text NOT NULL,
    plan text NOT NULL,
    interval text NOT NULL,
    status text NOT NULL,
    external_customer_id text,
    external_subscription_id text NOT NULL,
    external_price_id text,
    cancel_at_period_end boolean NOT NULL DEFAULT false,
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    provider_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS billing_subscriptions_provider_external_uq
    ON billing_subscriptions(provider, external_subscription_id);
CREATE INDEX IF NOT EXISTS ix_billing_subscriptions_user_id ON billing_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS ix_billing_subscriptions_provider ON billing_subscriptions(provider);
CREATE INDEX IF NOT EXISTS ix_billing_subscriptions_status ON billing_subscriptions(status);
CREATE INDEX IF NOT EXISTS ix_billing_subscriptions_external_customer_id ON billing_subscriptions(external_customer_id);

CREATE TABLE IF NOT EXISTS billing_provider_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    provider_event_id text NOT NULL,
    event_type text,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    processed_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS billing_provider_events_provider_event_uq
    ON billing_provider_events(provider, provider_event_id);
CREATE INDEX IF NOT EXISTS ix_billing_provider_events_provider ON billing_provider_events(provider);
